import Link from 'next/link'

export default function LandingPage() {
  return (
    <div className="flex flex-col min-h-screen">

      {/* Hero Section */}
      <section className="relative flex flex-col items-center justify-center text-center px-4 py-28 bg-gradient-to-b from-forest-900 via-forest-800 to-stone-900 text-white overflow-hidden">
        {/* Decorative mountain silhouette */}
        <div className="absolute inset-0 opacity-10 pointer-events-none select-none text-[18rem] leading-none flex items-end justify-center overflow-hidden">
          🏔️
        </div>

        <div className="relative z-10 max-w-3xl mx-auto">
          <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-white/10 text-sm font-medium mb-6 text-forest-200 border border-white/10">
            <span>🌿</span> Built for Sahyadri hikers
          </div>

          <h1 className="text-5xl sm:text-6xl font-bold leading-tight mb-6">
            Your Sahyadri<br />
            <span className="text-forest-400">hiking story</span>, finally home.
          </h1>

          <p className="text-lg sm:text-xl text-stone-300 leading-relaxed mb-10 max-w-2xl mx-auto">
            Log every fort you've conquered, every trail you've walked — past or present.
            Earn AI-generated badges, share photo memories, and discover your next Sahyadri adventure.
          </p>

          <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
            <Link
              href="/auth/signup"
              className="w-full sm:w-auto px-8 py-3.5 bg-forest-500 hover:bg-forest-400 text-white font-semibold rounded-xl transition-colors text-base shadow-lg shadow-forest-900/40"
            >
              Start your trek journal →
            </Link>
            <Link
              href="/trails"
              className="w-full sm:w-auto px-8 py-3.5 bg-white/10 hover:bg-white/20 text-white font-semibold rounded-xl transition-colors text-base border border-white/20"
            >
              Browse trails
            </Link>
          </div>
        </div>
      </section>

      {/* Features Grid */}
      <section className="py-20 px-4 bg-stone-50">
        <div className="max-w-5xl mx-auto">
          <h2 className="text-3xl font-bold text-center text-stone-900 mb-4">
            Everything a Sahyadri hiker needs
          </h2>
          <p className="text-center text-stone-500 mb-14 max-w-xl mx-auto">
            Not a generic hiking app. Built specifically for Maharashtra's forts and trails.
          </p>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
            {[
              {
                icon: '📓',
                title: 'Trek Memoir',
                desc: 'Log hikes you did years ago. Build a complete personal history of every summit and trail since day one.',
              },
              {
                icon: '🏅',
                title: 'AI-Generated Badges',
                desc: 'Complete a trek and earn a unique badge for that trail — generated by AI, cached forever, yours to keep.',
              },
              {
                icon: '📍',
                title: 'GPS Verification',
                desc: 'On-location? Get a Verified badge. Your browser checks your GPS — no app needed, no uploads.',
              },
              {
                icon: '🗺️',
                title: 'Trails Directory',
                desc: 'Explore forts and trails across Pune, Nashik, Konkan and the rest of the Sahyadri range.',
              },
              {
                icon: '📸',
                title: 'Photo Memories',
                desc: 'Link your Google Photos albums or Drive folders — we store the link, you keep the photos.',
              },
              {
                icon: '🌤️',
                title: 'Community Reports',
                desc: 'Real conditions from real hikers. Know if the trail is muddy, rocky, or perfect before you go.',
              },
            ].map((f) => (
              <div
                key={f.title}
                className="bg-white rounded-2xl p-6 border border-stone-100 shadow-sm hover:shadow-md transition-shadow"
              >
                <div className="text-3xl mb-4">{f.icon}</div>
                <h3 className="font-semibold text-stone-900 text-lg mb-2">{f.title}</h3>
                <p className="text-stone-500 text-sm leading-relaxed">{f.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Badge Showcase */}
      <section className="py-20 px-4 bg-forest-900 text-white">
        <div className="max-w-4xl mx-auto text-center">
          <h2 className="text-3xl font-bold mb-4">Collect your Sahyadri badges</h2>
          <p className="text-forest-200 mb-12 max-w-xl mx-auto">
            Every trail has a unique AI-generated badge. Complete a trek, earn the badge — it's yours forever on your dashboard.
          </p>
          <div className="flex flex-wrap justify-center gap-6 text-6xl">
            {['🏔️', '🌿', '🦅', '💧', '🌄', '⚡', '🌺', '🏯'].map((emoji, i) => (
              <div
                key={i}
                className="w-24 h-24 rounded-full bg-white/10 border border-white/20 flex items-center justify-center hover:scale-110 transition-transform cursor-default"
                title="Earn this by completing a trail"
              >
                {emoji}
              </div>
            ))}
          </div>
          <p className="text-forest-300 text-sm mt-8">
            Real badges are generated with AI — unique artwork for each trail and fort.
          </p>
        </div>
      </section>

      {/* CTA */}
      <section className="py-20 px-4 bg-stone-900 text-white text-center">
        <div className="max-w-2xl mx-auto">
          <h2 className="text-4xl font-bold mb-4">Ready to log your first trek?</h2>
          <p className="text-stone-400 mb-8">
            Free forever. No credit card. No fancy subscriptions.
          </p>
          <Link
            href="/auth/signup"
            className="inline-block px-10 py-4 bg-forest-500 hover:bg-forest-400 text-white font-bold rounded-xl transition-colors text-lg shadow-xl shadow-forest-900/50"
          >
            Create your hiker profile →
          </Link>
        </div>
      </section>

      {/* Footer */}
      <footer className="py-8 px-4 bg-stone-950 text-stone-500 text-center text-sm">
        <p>
          Sahyadri Trail Hub · Built with ❤️ for Maharashtra's hikers ·{' '}
          <span className="text-stone-600">Powered by Supabase + Vercel (free tier 🙏)</span>
        </p>
      </footer>
    </div>
  )
}
